[package]
name = "repodesk-desktop"
version = "0.1.0"
description = "RepoDesk local-first desktop cockpit"
edition = "2024"
publish = false

[lib]
name = "repodesk_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.23"
chrono.workspace = true
rusqlite.workspace = true
dirs.workspace = true
portable-pty = "0.9"
repodesk-core = { path = "../../../crates/repodesk-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
thiserror.workspace = true
ureq.workspace = true
tauri-plugin-global-shortcut = "2.0.0"
quick-xml = "0.41"

[dev-dependencies]
serial_test = "4"
tempfile.workspace = true
