use std::fs;

use crate::errors::RepoDeskResult;
use crate::git_workspace::run_git_captured as run_git;
use crate::init;
use crate::paths::RepoDeskPaths;
use crate::projects::get_active_project;
use crate::tasks::show_active_task;
use crate::tokens::{TokenEstimate, estimate_text, format_estimate};
use crate::utils::format_list;

/// Token budget for the Memory Brain slice injected into the full context pack.
const MEMORY_BUDGET_TOKENS: usize = 1_500;

#[derive(Debug, Clone)]
pub struct ContextBuildResult {
    pub context_file: String,
    pub token_estimate_file: String,
    pub estimate: TokenEstimate,
}

pub fn build_context() -> RepoDeskResult<ContextBuildResult> {
    init::init_home()?;

    let paths = RepoDeskPaths::resolve()?;
    let project = get_active_project()?;
    let task = show_active_task()?;

    let project_meta_dir = paths.project_dir(&project.name);

    let task_markdown = read_optional_file(&task.task_markdown_file);
    // Prefer the live, ranked Memory Brain slice; fall back to the legacy
    // memory.md artifact when the brain has no entries (or is unavailable).
    let memory = match crate::memory::retrieval::memory_slice(&project.name, MEMORY_BUDGET_TOKENS) {
        Ok(slice) if !slice.is_empty() => slice.markdown,
        _ => read_optional_file(&project_meta_dir.join("memory.md")),
    };
    let decisions = read_optional_file(&project_meta_dir.join("decisions.md"));
    let risks = read_optional_file(&project_meta_dir.join("risks.md"));

    let git_branch = run_git(&project.path, &["branch", "--show-current"]);
    let git_status = run_git(&project.path, &["status", "--short"]);
    let git_diff_stat = run_git(&project.path, &["diff", "--stat"]);
    let git_changed_files = run_git(&project.path, &["diff", "--name-only"]);

    let context = format!(
        r#"# RepoDesk Context Pack

## Project

Name: `{project_name}`
Path: `{project_path}`
Type: `{project_type}`
Main language: `{main_language}`

## Active Task

Id: `{task_id}`
Title: `{task_title}`
Status: `open`
Run dir: `{run_dir}`

## Task File

{task_markdown}

## Project Memory

{memory}

## Decisions

{decisions}

## Risks

{risks}

## Configured Checks

{checks}

## Context Ignore Rules

{ignore_rules}

## Git Branch

```txt
{git_branch}
```

## Git Status

```txt
{git_status}
```

## Git Diff Stat

```txt
{git_diff_stat}
```

## Git Changed Files

```txt
{git_changed_files}
```

## Notes For Agents

- This context pack is generated by RepoDesk.
- Do not assume this is the full repository.
- Use this as bounded task context.
- Ask for additional specific files only when needed.
- Do not run expensive checks repeatedly.
- Prefer local shell checks through RepoDesk.

"#,
        project_name = project.name,
        project_path = project.path.display(),
        project_type = project.project_type,
        main_language = project
            .main_language
            .clone()
            .unwrap_or_else(|| "unknown".to_string()),
        task_id = task.config.id,
        task_title = task.config.title,
        run_dir = task.config.run_dir.display(),
        task_markdown = trim_for_context(&task_markdown, 8_000),
        memory = trim_for_context(&memory, 6_000),
        decisions = trim_for_context(&decisions, 6_000),
        risks = trim_for_context(&risks, 6_000),
        checks = format_list(&project.checks),
        ignore_rules = format_list(&project.context_ignore),
        git_branch = git_branch.trim(),
        git_status = fallback_empty(git_status.trim(), "No git status output."),
        git_diff_stat = fallback_empty(git_diff_stat.trim(), "No git diff stat."),
        git_changed_files = fallback_empty(git_changed_files.trim(), "No changed files."),
    );

    let estimate = estimate_text(&context);

    let context_file = task.config.run_dir.join("context.md");
    let token_estimate_file = task.config.run_dir.join("token-estimate.txt");

    fs::write(&context_file, context)?;
    fs::write(&token_estimate_file, format_estimate(&estimate))?;

    let _ = crate::engineering::instrumentation::record_context_built(
        &task.config,
        &context_file.display().to_string(),
        &token_estimate_file.display().to_string(),
        estimate.estimated_tokens,
    );

    Ok(ContextBuildResult {
        context_file: context_file.display().to_string(),
        token_estimate_file: token_estimate_file.display().to_string(),
        estimate,
    })
}

pub fn estimate_active_context() -> RepoDeskResult<(String, TokenEstimate)> {
    let task = show_active_task()?;
    let context_file = task.config.run_dir.join("context.md");

    let content = fs::read_to_string(&context_file)?;
    let estimate = estimate_text(&content);

    Ok((context_file.display().to_string(), estimate))
}

fn read_optional_file(path: &std::path::Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|_| "Not available.".to_string())
}

fn trim_for_context(value: &str, max_chars: usize) -> String {
    if value.chars().count() <= max_chars {
        return value.to_string();
    }

    let trimmed = value.chars().take(max_chars).collect::<String>();

    format!("{trimmed}\n\n[RepoDesk: content trimmed for context budget]")
}

fn fallback_empty<'a>(value: &'a str, fallback: &'a str) -> &'a str {
    if value.is_empty() { fallback } else { value }
}
