use std::fs;

use sha2::{Digest, Sha256};

use crate::engineering::{ContextBuildTelemetry, ContextComponentTelemetry, record_context_build};
use crate::errors::RepoDeskResult;
use crate::git_workspace::run_git_captured as run_git;
use crate::init;
use crate::paths::RepoDeskPaths;
use crate::projects::get_active_project;
use crate::tasks::show_active_task;
use crate::tokens::{TokenEstimate, estimate_text, format_estimate};
use crate::utils::format_list;

/// Token budget for the Memory Brain slice injected into the full context pack.
const MEMORY_BUDGET_TOKENS: usize = 1_500;
const TASK_BUDGET_CHARS: usize = 8_000;
const PROJECT_MATERIAL_BUDGET_CHARS: usize = 6_000;

#[derive(Debug, Clone)]
pub struct ContextBuildResult {
    pub context_file: String,
    pub token_estimate_file: String,
    pub estimate: TokenEstimate,
}

#[derive(Clone, Copy)]
struct ContextPackInput<'a> {
    project_metadata: &'a str,
    task_metadata: &'a str,
    task_markdown: &'a str,
    memory: &'a str,
    decisions: &'a str,
    risks: &'a str,
    checks: &'a str,
    ignore_rules: &'a str,
    git_state: &'a str,
    agent_notes: &'a str,
}

pub fn build_context() -> RepoDeskResult<ContextBuildResult> {
    init::init_home()?;

    let paths = RepoDeskPaths::resolve()?;
    let project = get_active_project()?;
    let task = show_active_task()?;

    let project_meta_dir = paths.project_dir(&project.name);

    let task_markdown = read_optional_file(&task.task_markdown_file);
    // Prefer the live, ranked Memory Brain slice; fall back to the legacy
    // memory.md artifact when the brain has no entries (or is unavailable).
    let memory = match crate::memory::retrieval::memory_slice(&project.name, MEMORY_BUDGET_TOKENS) {
        Ok(slice) if !slice.is_empty() => slice.markdown,
        _ => read_optional_file(&project_meta_dir.join("memory.md")),
    };
    let decisions = read_optional_file(&project_meta_dir.join("decisions.md"));
    let risks = read_optional_file(&project_meta_dir.join("risks.md"));

    let git_branch = run_git(&project.path, &["branch", "--show-current"]);
    let git_status = run_git(&project.path, &["status", "--short"]);
    let git_diff_stat = run_git(&project.path, &["diff", "--stat"]);
    let git_changed_files = run_git(&project.path, &["diff", "--name-only"]);

    let project_metadata = format!(
        "Name: `{}`\nPath: `{}`\nType: `{}`\nMain language: `{}`",
        project.name,
        project.path.display(),
        project.project_type,
        project
            .main_language
            .clone()
            .unwrap_or_else(|| "unknown".to_string())
    );
    let task_metadata = format!(
        "Id: `{}`\nTitle: `{}`\nStatus: `open`\nRun dir: `{}`",
        task.config.id,
        task.config.title,
        task.config.run_dir.display()
    );
    let checks = format_list(&project.checks);
    let ignore_rules = format_list(&project.context_ignore);
    let git_state = format!(
        "## Git Branch\n\n```txt\n{}\n```\n\n## Git Status\n\n```txt\n{}\n```\n\n## Git Diff Stat\n\n```txt\n{}\n```\n\n## Git Changed Files\n\n```txt\n{}\n```",
        git_branch.trim(),
        fallback_empty(git_status.trim(), "No git status output."),
        fallback_empty(git_diff_stat.trim(), "No git diff stat."),
        fallback_empty(git_changed_files.trim(), "No changed files.")
    );
    let agent_notes = "- This context pack is generated by RepoDesk.\n- Do not assume this is the full repository.\n- Use this as bounded task context.\n- Ask for additional specific files only when needed.\n- Do not run expensive checks repeatedly.\n- Prefer local shell checks through RepoDesk.";

    let included_task_markdown = trim_for_context(&task_markdown, TASK_BUDGET_CHARS);
    let included_memory = trim_for_context(&memory, PROJECT_MATERIAL_BUDGET_CHARS);
    let included_decisions = trim_for_context(&decisions, PROJECT_MATERIAL_BUDGET_CHARS);
    let included_risks = trim_for_context(&risks, PROJECT_MATERIAL_BUDGET_CHARS);

    let candidate_input = ContextPackInput {
        project_metadata: &project_metadata,
        task_metadata: &task_metadata,
        task_markdown: &task_markdown,
        memory: &memory,
        decisions: &decisions,
        risks: &risks,
        checks: &checks,
        ignore_rules: &ignore_rules,
        git_state: &git_state,
        agent_notes,
    };
    let included_input = ContextPackInput {
        task_markdown: &included_task_markdown,
        memory: &included_memory,
        decisions: &included_decisions,
        risks: &included_risks,
        ..candidate_input
    };

    let candidate_context = render_context_pack(&candidate_input);
    let context = render_context_pack(&included_input);
    let candidate_estimate = estimate_text(&candidate_context);
    let estimate = estimate_text(&context);

    let components = vec![
        context_component("project_metadata", &project_metadata, &project_metadata),
        context_component("task_metadata", &task_metadata, &task_metadata),
        context_component("task", &task_markdown, &included_task_markdown),
        context_component("memory", &memory, &included_memory),
        context_component("decisions", &decisions, &included_decisions),
        context_component("risks", &risks, &included_risks),
        context_component("checks", &checks, &checks),
        context_component("ignore_rules", &ignore_rules, &ignore_rules),
        context_component("git_state", &git_state, &git_state),
        context_component("agent_notes", agent_notes, agent_notes),
    ];
    let context_fingerprint = sha256_hex(&context);

    let context_file = task.config.run_dir.join("context.md");
    let token_estimate_file = task.config.run_dir.join("token-estimate.txt");

    fs::write(&context_file, context)?;
    fs::write(&token_estimate_file, format_estimate(&estimate))?;

    let context_file = context_file.display().to_string();
    let token_estimate_file = token_estimate_file.display().to_string();

    // Engineering telemetry stays best-effort: a context pack that was built
    // successfully remains usable even if the append-only ledger cannot be
    // updated. The event stores counts and hashes, never raw component payloads.
    let _ = record_context_build(
        &task.config,
        ContextBuildTelemetry {
            context_file: &context_file,
            token_estimate_file: &token_estimate_file,
            included_tokens: estimate.estimated_tokens,
            candidate_tokens: candidate_estimate.estimated_tokens,
            context_fingerprint: &context_fingerprint,
            components: &components,
        },
    );

    Ok(ContextBuildResult {
        context_file,
        token_estimate_file,
        estimate,
    })
}

pub fn estimate_active_context() -> RepoDeskResult<(String, TokenEstimate)> {
    let task = show_active_task()?;
    let context_file = task.config.run_dir.join("context.md");

    let content = fs::read_to_string(&context_file)?;
    let estimate = estimate_text(&content);

    Ok((context_file.display().to_string(), estimate))
}

fn render_context_pack(input: &ContextPackInput<'_>) -> String {
    format!(
        r#"# RepoDesk Context Pack

## Project

{project_metadata}

## Active Task

{task_metadata}

## Task File

{task_markdown}

## Project Memory

{memory}

## Decisions

{decisions}

## Risks

{risks}

## Configured Checks

{checks}

## Context Ignore Rules

{ignore_rules}

{git_state}

## Notes For Agents

{agent_notes}

"#,
        project_metadata = input.project_metadata,
        task_metadata = input.task_metadata,
        task_markdown = input.task_markdown,
        memory = input.memory,
        decisions = input.decisions,
        risks = input.risks,
        checks = input.checks,
        ignore_rules = input.ignore_rules,
        git_state = input.git_state,
        agent_notes = input.agent_notes,
    )
}

fn context_component(name: &str, candidate: &str, included: &str) -> ContextComponentTelemetry {
    ContextComponentTelemetry {
        name: name.to_string(),
        candidate_tokens: estimate_text(candidate).estimated_tokens,
        included_tokens: estimate_text(included).estimated_tokens,
        trimmed: candidate != included,
        fingerprint: sha256_hex(included),
    }
}

fn sha256_hex(value: &str) -> String {
    hex::encode(Sha256::digest(value.as_bytes()))
}

fn read_optional_file(path: &std::path::Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|_| "Not available.".to_string())
}

fn trim_for_context(value: &str, max_chars: usize) -> String {
    if value.chars().count() <= max_chars {
        return value.to_string();
    }

    let trimmed = value.chars().take(max_chars).collect::<String>();

    format!("{trimmed}\n\n[RepoDesk: content trimmed for context budget]")
}

fn fallback_empty<'a>(value: &'a str, fallback: &'a str) -> &'a str {
    if value.is_empty() { fallback } else { value }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn component_telemetry_records_trimming_without_raw_text() {
        let component = context_component("task", "abcdef", "abc");

        assert_eq!(component.name, "task");
        assert!(component.trimmed);
        assert!(!component.fingerprint.contains("abc"));
        assert_eq!(component.fingerprint.len(), 64);
    }

    #[test]
    fn render_keeps_candidate_and_included_pack_structure_identical() {
        let input = ContextPackInput {
            project_metadata: "project",
            task_metadata: "task meta",
            task_markdown: "task body",
            memory: "memory",
            decisions: "decisions",
            risks: "risks",
            checks: "checks",
            ignore_rules: "ignore",
            git_state: "git",
            agent_notes: "notes",
        };

        let rendered = render_context_pack(&input);
        assert!(rendered.contains("## Task File\n\ntask body"));
        assert!(rendered.contains("## Project Memory\n\nmemory"));
        assert!(rendered.contains("## Notes For Agents\n\nnotes"));
    }
}
