pub mod access;
pub mod agents;
pub mod ai_adapters;
pub mod ai_discovery;
pub mod brain;

pub mod capabilities;
pub mod checks;
pub mod context;

pub mod desktop;
pub mod errors;
pub mod guard;
pub mod init;
pub mod judge;
pub mod module_registry;
pub mod paths;
pub mod peripherals;
pub mod persistence;
pub mod projects;
pub mod prompts;
pub mod safety;
pub mod security;
pub mod sessions;
pub mod tasks;
pub mod tokens;
pub mod ui_snapshot;
pub mod usage;
pub mod workflow;
pub mod workflow_doctor;

pub mod command_sandbox;
pub mod dashboard;
pub mod git_audit;
pub mod repo_map;
pub mod routing;
pub mod runtime;
pub mod sandbox;
pub mod smart_context;
pub use errors::{RepoDeskError, RepoDeskResult};
pub mod git_workspace;
pub mod project_token_check;
