use std::collections::BTreeSet;

use crate::errors::{RepoDeskError, RepoDeskResult};
use crate::persistence::db::init_db;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingRecord {
    pub id: i64,
    pub project: String,
    pub file_path: String,
    pub chunk_index: i64,
    pub content: String,
    pub embedding: Vec<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    pub file_path: String,
    pub chunk_index: i64,
    pub content: String,
    pub score: f32,
}

fn vec_to_blob(vec: &[f32]) -> Vec<u8> {
    let mut blob = Vec::with_capacity(vec.len() * 4);
    for &val in vec {
        blob.extend_from_slice(&val.to_le_bytes());
    }
    blob
}

fn blob_to_vec(blob: &[u8]) -> Vec<f32> {
    let mut vec = Vec::with_capacity(blob.len() / 4);
    for chunk in blob.chunks_exact(4) {
        let val = f32::from_le_bytes(chunk.try_into().unwrap());
        vec.push(val);
    }
    vec
}

fn dot_product(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b.iter()).map(|(x, y)| x * y).sum()
}

fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    let dot = dot_product(a, b);
    let norm_a = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let norm_b = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm_a == 0.0 || norm_b == 0.0 {
        0.0
    } else {
        dot / (norm_a * norm_b)
    }
}

/// Historical single-row insert kept for compatibility with older callers.
pub fn insert_embedding(
    project: &str,
    file_path: &str,
    chunk_index: i64,
    content: &str,
    embedding: &[f32],
) -> RepoDeskResult<()> {
    let conn = init_db()?;
    let blob = vec_to_blob(embedding);

    conn.execute(
        "INSERT INTO project_embeddings (project, file_path, chunk_index, content, embedding_blob)
         VALUES (?1, ?2, ?3, ?4, ?5)",
        (project, file_path, chunk_index, content, blob),
    )
    .map_err(|e| RepoDeskError::Database(format!("Failed to insert embedding: {e}")))?;

    Ok(())
}

pub fn delete_embeddings_for_file(project: &str, file_path: &str) -> RepoDeskResult<()> {
    let conn = init_db()?;
    conn.execute(
        "DELETE FROM project_embeddings WHERE project = ?1 AND file_path = ?2",
        (project, file_path),
    )
    .map_err(|e| RepoDeskError::Database(format!("Failed to delete file embeddings: {e}")))?;

    Ok(())
}

/// Return the fingerprint of the file version represented by the local semantic
/// index, or `None` for legacy/unindexed metadata.
pub fn embedding_file_fingerprint(
    project: &str,
    file_path: &str,
) -> RepoDeskResult<Option<String>> {
    let conn = init_db()?;
    let mut stmt = conn
        .prepare(
            "SELECT content_fingerprint FROM project_embedding_files
             WHERE project = ?1 AND file_path = ?2",
        )
        .map_err(|e| RepoDeskError::Database(format!("Failed to prepare embedding fingerprint query: {e}")))?;
    let mut rows = stmt
        .query((project, file_path))
        .map_err(|e| RepoDeskError::Database(format!("Failed to query embedding fingerprint: {e}")))?;
    let Some(row) = rows
        .next()
        .map_err(|e| RepoDeskError::Database(format!("Failed to read embedding fingerprint: {e}")))?
    else {
        return Ok(None);
    };
    row.get(0)
        .map(Some)
        .map_err(|e| RepoDeskError::Database(format!("Failed to decode embedding fingerprint: {e}")))
}

/// List files known to the fingerprint metadata table. Ordered output keeps
/// cleanup and tests deterministic.
pub fn list_indexed_files(project: &str) -> RepoDeskResult<Vec<String>> {
    let conn = init_db()?;
    let mut stmt = conn
        .prepare(
            "SELECT file_path FROM project_embedding_files
             WHERE project = ?1 ORDER BY file_path",
        )
        .map_err(|e| RepoDeskError::Database(format!("Failed to prepare indexed-file query: {e}")))?;
    let rows = stmt
        .query_map([project], |row| row.get::<_, String>(0))
        .map_err(|e| RepoDeskError::Database(format!("Failed to query indexed files: {e}")))?;
    rows.collect::<Result<Vec<_>, _>>()
        .map_err(|e| RepoDeskError::Database(format!("Failed to decode indexed file: {e}")))
}

/// Atomically replace all semantic chunks for one file and publish its new
/// fingerprint only after every embedding has already been generated by the
/// caller. A transaction failure rolls back to the previous known-good index.
pub fn replace_file_embeddings(
    project: &str,
    file_path: &str,
    fingerprint: &str,
    chunks: &[(String, Vec<f32>)],
) -> RepoDeskResult<()> {
    let mut conn = init_db()?;
    let tx = conn
        .transaction()
        .map_err(|e| RepoDeskError::Database(format!("Failed to begin embedding transaction: {e}")))?;
    tx.execute(
        "DELETE FROM project_embeddings WHERE project = ?1 AND file_path = ?2",
        (project, file_path),
    )
    .map_err(|e| RepoDeskError::Database(format!("Failed to replace file embeddings: {e}")))?;

    for (index, (content, embedding)) in chunks.iter().enumerate() {
        tx.execute(
            "INSERT INTO project_embeddings (project, file_path, chunk_index, content, embedding_blob)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            rusqlite::params![project, file_path, index as i64, content, vec_to_blob(embedding)],
        )
        .map_err(|e| RepoDeskError::Database(format!("Failed to insert replacement embedding: {e}")))?;
    }

    tx.execute(
        "INSERT INTO project_embedding_files (project, file_path, content_fingerprint, indexed_at)
         VALUES (?1, ?2, ?3, ?4)
         ON CONFLICT(project, file_path) DO UPDATE SET
             content_fingerprint = excluded.content_fingerprint,
             indexed_at = excluded.indexed_at",
        (
            project,
            file_path,
            fingerprint,
            chrono::Utc::now().to_rfc3339(),
        ),
    )
    .map_err(|e| RepoDeskError::Database(format!("Failed to update embedding fingerprint: {e}")))?;

    tx.commit()
        .map_err(|e| RepoDeskError::Database(format!("Failed to commit embedding transaction: {e}")))?;
    Ok(())
}

/// Delete both semantic chunks and fingerprint metadata for a file that is no
/// longer tracked by the repository.
pub fn delete_indexed_file(project: &str, file_path: &str) -> RepoDeskResult<()> {
    let mut conn = init_db()?;
    let tx = conn
        .transaction()
        .map_err(|e| RepoDeskError::Database(format!("Failed to begin embedding cleanup: {e}")))?;
    tx.execute(
        "DELETE FROM project_embeddings WHERE project = ?1 AND file_path = ?2",
        (project, file_path),
    )
    .map_err(|e| RepoDeskError::Database(format!("Failed to delete stale embeddings: {e}")))?;
    tx.execute(
        "DELETE FROM project_embedding_files WHERE project = ?1 AND file_path = ?2",
        (project, file_path),
    )
    .map_err(|e| RepoDeskError::Database(format!("Failed to delete stale embedding metadata: {e}")))?;
    tx.commit()
        .map_err(|e| RepoDeskError::Database(format!("Failed to commit embedding cleanup: {e}")))?;
    Ok(())
}

pub fn search_similar(
    project: &str,
    query_embedding: &[f32],
    limit: usize,
) -> RepoDeskResult<Vec<SearchResult>> {
    let conn = init_db()?;
    let mut stmt = conn
        .prepare("SELECT file_path, chunk_index, content, embedding_blob FROM project_embeddings WHERE project = ?1")
        .map_err(|e| RepoDeskError::Database(format!("Failed to prepare search query: {e}")))?;

    let mut rows = stmt
        .query([project])
        .map_err(|e| RepoDeskError::Database(format!("Failed to execute search query: {e}")))?;

    let mut results = Vec::new();
    while let Some(row) = rows
        .next()
        .map_err(|e| RepoDeskError::Database(format!("Failed to fetch search row: {e}")))?
    {
        let file_path: String = row
            .get(0)
            .map_err(|e| RepoDeskError::Database(format!("Failed to decode embedding path: {e}")))?;
        let chunk_index: i64 = row
            .get(1)
            .map_err(|e| RepoDeskError::Database(format!("Failed to decode embedding chunk: {e}")))?;
        let content: String = row
            .get(2)
            .map_err(|e| RepoDeskError::Database(format!("Failed to decode embedding content: {e}")))?;
        let blob: Vec<u8> = row
            .get(3)
            .map_err(|e| RepoDeskError::Database(format!("Failed to decode embedding vector: {e}")))?;

        let embedding = blob_to_vec(&blob);
        let score = cosine_similarity(query_embedding, &embedding);

        results.push(SearchResult {
            file_path,
            chunk_index,
            content,
            score,
        });
    }

    results.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    results.truncate(limit);

    Ok(results)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedding_blob_round_trips() {
        let values = vec![0.0, 1.25, -3.5, f32::MIN_POSITIVE];
        assert_eq!(blob_to_vec(&vec_to_blob(&values)), values);
    }

    #[test]
    fn cosine_similarity_is_stable_for_zero_vectors() {
        assert_eq!(cosine_similarity(&[0.0, 0.0], &[1.0, 2.0]), 0.0);
    }

    #[test]
    fn indexed_file_sets_remain_deterministic() {
        let set = BTreeSet::from(["z.rs", "a.rs"]);
        assert_eq!(set.into_iter().collect::<Vec<_>>(), vec!["a.rs", "z.rs"]);
    }
}
